"""added match percentage to user skill model

Revision ID: 57d7c858541f
Revises: 829ca527c60c
Create Date: 2026-02-28 19:40:03.273803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d7c858541f'
down_revision: Union[str, Sequence[str], None] = '829ca527c60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('match_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'match_percentage')
    # ### end Alembic commands ###
