"""add exchange_rates table

Revision ID: 594c070fbba3
Revises: 5ae4b60d61f5
Create Date: 2026-03-29 16:21:38.574569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594c070fbba3'
down_revision: Union[str, Sequence[str], None] = '5ae4b60d61f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Constraint might not exist in some environments; drop safely.
    op.execute(sa.text("ALTER TABLE exchange_rates DROP CONSTRAINT IF EXISTS uq_exchange_rates"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_exchange_rates'), 'exchange_rates', ['rate_date', 'currency_code', 'source'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
