"""add exchange_rates table

Revision ID: 5ae4b60d61f5
Revises: 7b3f1a2d6c4e
Create Date: 2026-03-29 14:40:30.705679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae4b60d61f5'
down_revision: Union[str, Sequence[str], None] = '7b3f1a2d6c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('rate_value_kzt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_per_unit_kzt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
