"""add exchange_rates table

Revision ID: 80c5207116ff
Revises: ce9df42b6626
Create Date: 2026-03-29 16:27:23.657318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c5207116ff'
down_revision: Union[str, Sequence[str], None] = 'ce9df42b6626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exchange_rates', 'exchange_rates', ['rate_date', 'currency_code', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exchange_rates', 'exchange_rates', type_='unique')
    # ### end Alembic commands ###
