"""added relation between direction and users

Revision ID: 829ca527c60c
Revises: da2bbb2a23b9
Create Date: 2026-02-25 19:50:11.350744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829ca527c60c'
down_revision: Union[str, Sequence[str], None] = 'da2bbb2a23b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('direction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'directions', ['direction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'direction_id')
    # ### end Alembic commands ###
