"""added question and user question models

Revision ID: c495c006dc9c
Revises: 57d7c858541f
Create Date: 2026-03-04 16:50:43.655286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c495c006dc9c'
down_revision: Union[str, Sequence[str], None] = '57d7c858541f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ideal_answer', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_updated_at'), 'questions', ['updated_at'], unique=False)
    op.create_table('user_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SATISFACTORY', 'UNSATISFACTORY', name='question_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_questions_created_at'), 'user_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_questions_id'), 'user_questions', ['id'], unique=False)
    op.create_index(op.f('ix_user_questions_question_id'), 'user_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_questions_updated_at'), 'user_questions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_questions_user_id'), 'user_questions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_questions_user_id'), table_name='user_questions')
    op.drop_index(op.f('ix_user_questions_updated_at'), table_name='user_questions')
    op.drop_index(op.f('ix_user_questions_question_id'), table_name='user_questions')
    op.drop_index(op.f('ix_user_questions_id'), table_name='user_questions')
    op.drop_index(op.f('ix_user_questions_created_at'), table_name='user_questions')
    op.drop_table('user_questions')
    op.drop_index(op.f('ix_questions_updated_at'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
