"""added question text to interview question

Revision ID: d1e2bd92fa48
Revises: e06bf5c4c29b
Create Date: 2026-03-04 21:22:59.639440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2bd92fa48'
down_revision: Union[str, Sequence[str], None] = 'e06bf5c4c29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('question_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'question_text')
    # ### end Alembic commands ###
