"""added direction and salary tables

Revision ID: da2bbb2a23b9
Revises: 1886e03d0801
Create Date: 2026-02-25 18:37:01.432709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2bbb2a23b9'
down_revision: Union[str, Sequence[str], None] = '1886e03d0801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directions_created_at'), 'directions', ['created_at'], unique=False)
    op.create_index(op.f('ix_directions_id'), 'directions', ['id'], unique=False)
    op.create_index(op.f('ix_directions_name'), 'directions', ['name'], unique=True)
    op.create_index(op.f('ix_directions_updated_at'), 'directions', ['updated_at'], unique=False)
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction_id', 'city_id', name='uq_direction_city_salary')
    )
    op.create_index(op.f('ix_salaries_created_at'), 'salaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_index(op.f('ix_salaries_updated_at'), 'salaries', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skill', 'user_skills', type_='unique')
    op.drop_index(op.f('ix_salaries_updated_at'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_created_at'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_index(op.f('ix_directions_updated_at'), table_name='directions')
    op.drop_index(op.f('ix_directions_name'), table_name='directions')
    op.drop_index(op.f('ix_directions_id'), table_name='directions')
    op.drop_index(op.f('ix_directions_created_at'), table_name='directions')
    op.drop_table('directions')
    # ### end Alembic commands ###
